[package]
name = "test_lib1234"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "testing my lib"
repository = "https://github.com/nkien0204/test_lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
